apiVersion: v1
kind: Service
metadata:
  name: cv-service
spec:
  type: NodePort
  selector:
    app: cv-service
  ports:
    - port: 8003
      targetPort: 8003
      nodePort: 30003
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cv-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cv-service
  template:
    metadata:
      labels:
        app: cv-service
    spec:
      containers:
      - name: cv-service
        image: nutritionapp-cv_service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8003
        env:
        - name: DATABASE_URL
          value: "postgresql://user:password@db:5432/app_db"